
# import data
```{r}
transactions = read.table("Transactions and customer attributes.txt", sep="\t", header = TRUE)
store_attributes <- read.csv("store attributes.csv")
summary(transactions)
```

# data exploring and processing for Q1.
```{r}
online <- transactions[transactions$brand_number==1, ]
online$return_date <- NULL
online$return_store <- NULL
online$time_to_return <- NULL
complete_online <- online[complete.cases(online),]
summary(complete_online)

# extract the useful variables for Q1
aggregate_daily_sales <- aggregate(complete_online[c("net_purchase_amount")],by=list(complete_online$purchase_date,complete_online$day,complete_online$month_dummy,complete_online$month_index,complete_online$year,complete_online$store_number), sum)
colnames(aggregate_daily_sales)[1] <- "purchase_day"
colnames(aggregate_daily_sales)[2] <- "day"
colnames(aggregate_daily_sales)[3] <- "month_dummy"
colnames(aggregate_daily_sales)[4] <- "month_index"
colnames(aggregate_daily_sales)[5] <- "year"
colnames(aggregate_daily_sales)[6] <- "store_number"
colnames(aggregate_daily_sales)[7] <- "daily_sales"

aggregate_ave_daily_price <- aggregate(complete_online[c("net_purchase_amount")],                           by=list(complete_online$day,complete_online$store_number), mean)
colnames(aggregate_ave_daily_price)[1] <- "day"
colnames(aggregate_ave_daily_price)[2] <- "store_number"
colnames(aggregate_ave_daily_price)[3] <- "ave_price"

library(plyr)
aggregate_daily_sales_quanity <-count(complete_online,c("day","store_number"))
colnames(aggregate_daily_sales_quanity)[3] <- "daily_sales_quanity"

first_merge <- merge(aggregate_daily_sales, aggregate_ave_daily_price, by=c("day","store_number"), all=F)

onlineQ1 <- merge(first_merge,aggregate_daily_sales_quanity,by=c("day","store_number"), all=F)

# final data set for Q1

write.csv(file="onlineQ1.csv",onlineQ1)

```

# data exploring and processing for Q2.
```{r}
physcial <- transactions[transactions$brand_number!=1,]

physcial$return_date <- NULL
physcial$return_store <- NULL
physcial$time_to_return <- NULL

physical_complete <- physcial[complete.cases(physcial),]

physcial_store_arttributes <- store_attributes[store_attributes$Brand_number!=1,]

physcial_month_aggregate <- aggregate(physical_complete[c("net_purchase_amount")],
                by=list(physical_complete$month_dummy,physical_complete$month_index,physical_complete$year,
                physical_complete$store_number,physical_complete$brand_number), sum)

colnames(physcial_month_aggregate)[1] <- "month_dummy"
colnames(physcial_month_aggregate)[2] <- "month_index"
colnames(physcial_month_aggregate)[3] <- "year"
colnames(physcial_month_aggregate)[4] <- "store_number"
colnames(physcial_month_aggregate)[5] <- "brand_number"
colnames(physcial_month_aggregate)[6] <- "monthly_sales"

aggregate_monthly_sales_quanity <-count(physical_complete,c("month_index","store_number"))
colnames(aggregate_monthly_sales_quanity)[3] <- "monthly_sales_quanity"

merge1 <- merge(physcial_store_arttributes,physcial_month_aggregate, 
                    by=c("store_number","month_index","year"), all=F)
physicalQ2 <- merge(merge1,aggregate_monthly_sales_quanity, by=c("store_number","month_index"), all=F)

# delete NA rows
physicalQ2 <- physicalQ2[complete.cases(physicalQ2),]

# final data set for Q2
write.csv(file="physicalQ2.csv",physicalQ2)

```

# data exploring and processing for Q5.
```{r}
counts = data.frame(table(transactions$customer_id))
colnames(counts) = c("customer_id", "units") 
merged = merge(counts, transactions, by = "customer_id", all = TRUE)
merged$sku = NULL
merged$return_date = NULL
merged$return_store = NULL
merged$time_to_return = NULL
merged$purchase_date = NULL
merged$sales_assoc_1 = NULL
merged1 = merged[!(rowSums(is.na(merged))),]

newdata5 = aggregate(net_purchase_amount~customer_id+month_index+Brand_number+store_number+gender+age_band+
                       est_income_code + ethnic_code + homeowner_code + length_of_residence + child + units , data = merged1 , sum)
newdata5$post_policy = ifelse((newdata5$month_index == 45 | newdata5$month_index == 46 | newdata5$month_index == 47| newdata5$month_index ==48|
                                 newdata5$month_index == 49 | newdata5$month_index == 50 ), 0, 1)
newdata5$study_group = ifelse(newdata5$Brand_number == 8 | (newdata5$Brand_number == 1 & newdata5$store_number == 10) , 0 , 1)

filter5 = newdata5$post_policy == 0 
merged2 = newdata5[filter5,]
filter6 = newdata5$post_policy == 1 
merged3 = newdata5[filter6, ]

merged2_X1_0 = aggregate(net_purchase_amount~customer_id+post_policy+study_group+gender+ age_band+ est_income_code + ethnic_code + homeowner_code + length_of_residence + child + units , data = merged2 , sum)
merged3_X1_1 = aggregate(net_purchase_amount~customer_id+post_policy+study_group+gender+ age_band+ est_income_code + ethnic_code + homeowner_code + length_of_residence + child + units , data = merged3 , sum)
merged_final = merge(merged2_X1_0,merged3_X1_1, by = c("customer_id","units"), all= TRUE)
merged_final1 = merged_final[!(rowSums(is.na(merged_final))),]
filter7 = merged_final1$study_group.x + merged_final1$study_group.y == 2 | merged_final1$study_group.x + merged_final1$study_group.y == 0 
merged_final2 = merged_final1[filter7, ]

install.packages("dplyr")
library(dplyr)
merged_final3 = select(merged_final2,customer_id, post_policy.x, study_group.x, net_purchase_amount.x,units)
merged_final4 = select(merged_final2,customer_id, post_policy.y, study_group.y, net_purchase_amount.y,units)
colnames(merged_final3) = c("customer_id","post_policy","study_group","net_purchase_amount","units")
colnames(merged_final4) = c("customer_id","post_policy","study_group","net_purchase_amount", "units")

merged_final5 = merge(merged_final3,merged_final4,by = c("customer_id", "post_policy","study_group","net_purchase_amount", "units"), all = TRUE )
newdata5_selected = select(newdata5, customer_id, gender, age_band, est_income_code, ethnic_code, homeowner_code, length_of_residence, child)
merged_final6 = merge(merged_final5, newdata5_selected, by = c("customer_id"), all = TRUE )
finalQ5 = merged_final6 [!(rowSums(is.na(merged_final6))),]
finalQ5 = unique(finalQ5)
str(finalQ5)
finalQ5$gender = ifelse(finalQ5$gender == "F", "F", ifelse(finalQ5$gender == "M", "M", "U")) #put U to missing value as well
finalQ5$gender = factor(finalQ5$gender) 

# final data set for Q5
write.csv(file="finalQ5.csv",finalQ5)
```




